//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("KelasiModel", "FK_dbo_Categories_dbo_Topics_Topic_TopicId", "Topic", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kelasi.UI.Web.Data.Topic), "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kelasi.UI.Web.Data.Category), true)]
[assembly: EdmRelationshipAttribute("KelasiModel", "FK_dbo_Courses_dbo_Categories_Category_CategoryId", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kelasi.UI.Web.Data.Category), "Cours", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kelasi.UI.Web.Data.Cours), true)]
[assembly: EdmRelationshipAttribute("KelasiModel", "FK_dbo_Courses_dbo_Languages_Language_LanguageId", "Language", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kelasi.UI.Web.Data.Language), "Cours", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kelasi.UI.Web.Data.Cours), true)]
[assembly: EdmRelationshipAttribute("KelasiModel", "FK_dbo_Courses_dbo_Topics_Topic_TopicId", "Topic", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kelasi.UI.Web.Data.Topic), "Cours", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kelasi.UI.Web.Data.Cours), true)]
[assembly: EdmRelationshipAttribute("KelasiModel", "FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId", "Users_Authors", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kelasi.UI.Web.Data.Users_Authors), "Cours", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kelasi.UI.Web.Data.Cours), true)]
[assembly: EdmRelationshipAttribute("KelasiModel", "FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId1", "Users_Authors", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kelasi.UI.Web.Data.Users_Authors), "Cours", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kelasi.UI.Web.Data.Cours), true)]
[assembly: EdmRelationshipAttribute("KelasiModel", "FK_dbo_Courses_dbo_Users_Authors_AuthorI_AuthorId", "Users_Authors", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kelasi.UI.Web.Data.Users_Authors), "Cours", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kelasi.UI.Web.Data.Cours), true)]
[assembly: EdmRelationshipAttribute("KelasiModel", "FK_dbo_Users_Authors_dbo_Users_User_UserId", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kelasi.UI.Web.Data.User), "Users_Authors", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kelasi.UI.Web.Data.Users_Authors), true)]

#endregion

namespace Kelasi.UI.Web.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KelasiEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KelasiEntities object using the connection string found in the 'KelasiEntities' section of the application configuration file.
        /// </summary>
        public KelasiEntities() : base("name=KelasiEntities", "KelasiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KelasiEntities object.
        /// </summary>
        public KelasiEntities(string connectionString) : base(connectionString, "KelasiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KelasiEntities object.
        /// </summary>
        public KelasiEntities(EntityConnection connection) : base(connection, "KelasiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cours> Courses
        {
            get
            {
                if ((_Courses == null))
                {
                    _Courses = base.CreateObjectSet<Cours>("Courses");
                }
                return _Courses;
            }
        }
        private ObjectSet<Cours> _Courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Language> Languages
        {
            get
            {
                if ((_Languages == null))
                {
                    _Languages = base.CreateObjectSet<Language>("Languages");
                }
                return _Languages;
            }
        }
        private ObjectSet<Language> _Languages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Plan> Plans
        {
            get
            {
                if ((_Plans == null))
                {
                    _Plans = base.CreateObjectSet<Plan>("Plans");
                }
                return _Plans;
            }
        }
        private ObjectSet<Plan> _Plans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Topic> Topics
        {
            get
            {
                if ((_Topics == null))
                {
                    _Topics = base.CreateObjectSet<Topic>("Topics");
                }
                return _Topics;
            }
        }
        private ObjectSet<Topic> _Topics;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users_Authors> Users_Authors
        {
            get
            {
                if ((_Users_Authors == null))
                {
                    _Users_Authors = base.CreateObjectSet<Users_Authors>("Users_Authors");
                }
                return _Users_Authors;
            }
        }
        private ObjectSet<Users_Authors> _Users_Authors;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourses(Cours cours)
        {
            base.AddObject("Courses", cours);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Languages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLanguages(Language language)
        {
            base.AddObject("Languages", language);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Plans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlans(Plan plan)
        {
            base.AddObject("Plans", plan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Topics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTopics(Topic topic)
        {
            base.AddObject("Topics", topic);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users_Authors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers_Authors(Users_Authors users_Authors)
        {
            base.AddObject("Users_Authors", users_Authors);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KelasiModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        public static Category CreateCategory(global::System.Int32 categoryId)
        {
            Category category = new Category();
            category.CategoryId = categoryId;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                if (_CategoryId != value)
                {
                    OnCategoryIdChanging(value);
                    ReportPropertyChanging("CategoryId");
                    _CategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryId");
                    OnCategoryIdChanged();
                }
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Topic_TopicId
        {
            get
            {
                return _Topic_TopicId;
            }
            set
            {
                OnTopic_TopicIdChanging(value);
                ReportPropertyChanging("Topic_TopicId");
                _Topic_TopicId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Topic_TopicId");
                OnTopic_TopicIdChanged();
            }
        }
        private Nullable<global::System.Int32> _Topic_TopicId;
        partial void OnTopic_TopicIdChanging(Nullable<global::System.Int32> value);
        partial void OnTopic_TopicIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Categories_dbo_Topics_Topic_TopicId", "Topic")]
        public Topic Topic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Topic>("KelasiModel.FK_dbo_Categories_dbo_Topics_Topic_TopicId", "Topic").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Topic>("KelasiModel.FK_dbo_Categories_dbo_Topics_Topic_TopicId", "Topic").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Topic> TopicReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Topic>("KelasiModel.FK_dbo_Categories_dbo_Topics_Topic_TopicId", "Topic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Topic>("KelasiModel.FK_dbo_Categories_dbo_Topics_Topic_TopicId", "Topic", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Categories_Category_CategoryId", "Cours")]
        public EntityCollection<Cours> Courses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Categories_Category_CategoryId", "Cours");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Categories_Category_CategoryId", "Cours", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KelasiModel", Name="Cours")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cours : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cours object.
        /// </summary>
        /// <param name="courseId">Initial value of the CourseId property.</param>
        /// <param name="releasedDate">Initial value of the ReleasedDate property.</param>
        /// <param name="updatedDate">Initial value of the UpdatedDate property.</param>
        /// <param name="duration">Initial value of the Duration property.</param>
        /// <param name="numberOfviewers">Initial value of the NumberOfviewers property.</param>
        /// <param name="numberOfSubscribers">Initial value of the NumberOfSubscribers property.</param>
        /// <param name="size">Initial value of the Size property.</param>
        public static Cours CreateCours(global::System.Int32 courseId, global::System.DateTime releasedDate, global::System.DateTime updatedDate, global::System.Int32 duration, global::System.Int32 numberOfviewers, global::System.Int32 numberOfSubscribers, global::System.Int32 size)
        {
            Cours cours = new Cours();
            cours.CourseId = courseId;
            cours.ReleasedDate = releasedDate;
            cours.UpdatedDate = updatedDate;
            cours.Duration = duration;
            cours.NumberOfviewers = numberOfviewers;
            cours.NumberOfSubscribers = numberOfSubscribers;
            cours.Size = size;
            return cours;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CourseId
        {
            get
            {
                return _CourseId;
            }
            set
            {
                if (_CourseId != value)
                {
                    OnCourseIdChanging(value);
                    ReportPropertyChanging("CourseId");
                    _CourseId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CourseId");
                    OnCourseIdChanged();
                }
            }
        }
        private global::System.Int32 _CourseId;
        partial void OnCourseIdChanging(global::System.Int32 value);
        partial void OnCourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReleasedDate
        {
            get
            {
                return _ReleasedDate;
            }
            set
            {
                OnReleasedDateChanging(value);
                ReportPropertyChanging("ReleasedDate");
                _ReleasedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReleasedDate");
                OnReleasedDateChanged();
            }
        }
        private global::System.DateTime _ReleasedDate;
        partial void OnReleasedDateChanging(global::System.DateTime value);
        partial void OnReleasedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.Int32 _Duration;
        partial void OnDurationChanging(global::System.Int32 value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumberOfviewers
        {
            get
            {
                return _NumberOfviewers;
            }
            set
            {
                OnNumberOfviewersChanging(value);
                ReportPropertyChanging("NumberOfviewers");
                _NumberOfviewers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfviewers");
                OnNumberOfviewersChanged();
            }
        }
        private global::System.Int32 _NumberOfviewers;
        partial void OnNumberOfviewersChanging(global::System.Int32 value);
        partial void OnNumberOfviewersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumberOfSubscribers
        {
            get
            {
                return _NumberOfSubscribers;
            }
            set
            {
                OnNumberOfSubscribersChanging(value);
                ReportPropertyChanging("NumberOfSubscribers");
                _NumberOfSubscribers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfSubscribers");
                OnNumberOfSubscribersChanged();
            }
        }
        private global::System.Int32 _NumberOfSubscribers;
        partial void OnNumberOfSubscribersChanging(global::System.Int32 value);
        partial void OnNumberOfSubscribersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.Int32 _Size;
        partial void OnSizeChanging(global::System.Int32 value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Category_CategoryId
        {
            get
            {
                return _Category_CategoryId;
            }
            set
            {
                OnCategory_CategoryIdChanging(value);
                ReportPropertyChanging("Category_CategoryId");
                _Category_CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Category_CategoryId");
                OnCategory_CategoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _Category_CategoryId;
        partial void OnCategory_CategoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnCategory_CategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Topic_TopicId
        {
            get
            {
                return _Topic_TopicId;
            }
            set
            {
                OnTopic_TopicIdChanging(value);
                ReportPropertyChanging("Topic_TopicId");
                _Topic_TopicId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Topic_TopicId");
                OnTopic_TopicIdChanged();
            }
        }
        private Nullable<global::System.Int32> _Topic_TopicId;
        partial void OnTopic_TopicIdChanging(Nullable<global::System.Int32> value);
        partial void OnTopic_TopicIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AuthorI_AuthorId
        {
            get
            {
                return _AuthorI_AuthorId;
            }
            set
            {
                OnAuthorI_AuthorIdChanging(value);
                ReportPropertyChanging("AuthorI_AuthorId");
                _AuthorI_AuthorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorI_AuthorId");
                OnAuthorI_AuthorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AuthorI_AuthorId;
        partial void OnAuthorI_AuthorIdChanging(Nullable<global::System.Int32> value);
        partial void OnAuthorI_AuthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Language_LanguageId
        {
            get
            {
                return _Language_LanguageId;
            }
            set
            {
                OnLanguage_LanguageIdChanging(value);
                ReportPropertyChanging("Language_LanguageId");
                _Language_LanguageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Language_LanguageId");
                OnLanguage_LanguageIdChanged();
            }
        }
        private Nullable<global::System.Int32> _Language_LanguageId;
        partial void OnLanguage_LanguageIdChanging(Nullable<global::System.Int32> value);
        partial void OnLanguage_LanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Author_AuthorId
        {
            get
            {
                return _Author_AuthorId;
            }
            set
            {
                OnAuthor_AuthorIdChanging(value);
                ReportPropertyChanging("Author_AuthorId");
                _Author_AuthorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Author_AuthorId");
                OnAuthor_AuthorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _Author_AuthorId;
        partial void OnAuthor_AuthorIdChanging(Nullable<global::System.Int32> value);
        partial void OnAuthor_AuthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Author_AuthorId1
        {
            get
            {
                return _Author_AuthorId1;
            }
            set
            {
                OnAuthor_AuthorId1Changing(value);
                ReportPropertyChanging("Author_AuthorId1");
                _Author_AuthorId1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Author_AuthorId1");
                OnAuthor_AuthorId1Changed();
            }
        }
        private Nullable<global::System.Int32> _Author_AuthorId1;
        partial void OnAuthor_AuthorId1Changing(Nullable<global::System.Int32> value);
        partial void OnAuthor_AuthorId1Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Categories_Category_CategoryId", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("KelasiModel.FK_dbo_Courses_dbo_Categories_Category_CategoryId", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("KelasiModel.FK_dbo_Courses_dbo_Categories_Category_CategoryId", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("KelasiModel.FK_dbo_Courses_dbo_Categories_Category_CategoryId", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("KelasiModel.FK_dbo_Courses_dbo_Categories_Category_CategoryId", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Languages_Language_LanguageId", "Language")]
        public Language Language
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("KelasiModel.FK_dbo_Courses_dbo_Languages_Language_LanguageId", "Language").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("KelasiModel.FK_dbo_Courses_dbo_Languages_Language_LanguageId", "Language").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Language> LanguageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("KelasiModel.FK_dbo_Courses_dbo_Languages_Language_LanguageId", "Language");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Language>("KelasiModel.FK_dbo_Courses_dbo_Languages_Language_LanguageId", "Language", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Topics_Topic_TopicId", "Topic")]
        public Topic Topic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Topic>("KelasiModel.FK_dbo_Courses_dbo_Topics_Topic_TopicId", "Topic").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Topic>("KelasiModel.FK_dbo_Courses_dbo_Topics_Topic_TopicId", "Topic").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Topic> TopicReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Topic>("KelasiModel.FK_dbo_Courses_dbo_Topics_Topic_TopicId", "Topic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Topic>("KelasiModel.FK_dbo_Courses_dbo_Topics_Topic_TopicId", "Topic", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId", "Users_Authors")]
        public Users_Authors Users_Authors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId", "Users_Authors").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId", "Users_Authors").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users_Authors> Users_AuthorsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId", "Users_Authors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId", "Users_Authors", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId1", "Users_Authors")]
        public Users_Authors Users_Authors1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId1", "Users_Authors").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId1", "Users_Authors").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users_Authors> Users_Authors1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId1", "Users_Authors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId1", "Users_Authors", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Users_Authors_AuthorI_AuthorId", "Users_Authors")]
        public Users_Authors Users_Authors2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_AuthorI_AuthorId", "Users_Authors").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_AuthorI_AuthorId", "Users_Authors").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users_Authors> Users_Authors2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_AuthorI_AuthorId", "Users_Authors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users_Authors>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_AuthorI_AuthorId", "Users_Authors", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KelasiModel", Name="Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Language object.
        /// </summary>
        /// <param name="languageId">Initial value of the LanguageId property.</param>
        public static Language CreateLanguage(global::System.Int32 languageId)
        {
            Language language = new Language();
            language.LanguageId = languageId;
            return language;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                if (_LanguageId != value)
                {
                    OnLanguageIdChanging(value);
                    ReportPropertyChanging("LanguageId");
                    _LanguageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LanguageId");
                    OnLanguageIdChanged();
                }
            }
        }
        private global::System.Int32 _LanguageId;
        partial void OnLanguageIdChanging(global::System.Int32 value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Languages_Language_LanguageId", "Cours")]
        public EntityCollection<Cours> Courses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Languages_Language_LanguageId", "Cours");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Languages_Language_LanguageId", "Cours", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KelasiModel", Name="Plan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Plan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Plan object.
        /// </summary>
        /// <param name="planId">Initial value of the PlanId property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static Plan CreatePlan(global::System.Int32 planId, global::System.Decimal price)
        {
            Plan plan = new Plan();
            plan.PlanId = planId;
            plan.Price = price;
            return plan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlanId
        {
            get
            {
                return _PlanId;
            }
            set
            {
                if (_PlanId != value)
                {
                    OnPlanIdChanging(value);
                    ReportPropertyChanging("PlanId");
                    _PlanId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlanId");
                    OnPlanIdChanged();
                }
            }
        }
        private global::System.Int32 _PlanId;
        partial void OnPlanIdChanging(global::System.Int32 value);
        partial void OnPlanIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KelasiModel", Name="Topic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Topic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Topic object.
        /// </summary>
        /// <param name="topicId">Initial value of the TopicId property.</param>
        public static Topic CreateTopic(global::System.Int32 topicId)
        {
            Topic topic = new Topic();
            topic.TopicId = topicId;
            return topic;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TopicId
        {
            get
            {
                return _TopicId;
            }
            set
            {
                if (_TopicId != value)
                {
                    OnTopicIdChanging(value);
                    ReportPropertyChanging("TopicId");
                    _TopicId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TopicId");
                    OnTopicIdChanged();
                }
            }
        }
        private global::System.Int32 _TopicId;
        partial void OnTopicIdChanging(global::System.Int32 value);
        partial void OnTopicIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Categories_dbo_Topics_Topic_TopicId", "Category")]
        public EntityCollection<Category> Categories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Category>("KelasiModel.FK_dbo_Categories_dbo_Topics_Topic_TopicId", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Category>("KelasiModel.FK_dbo_Categories_dbo_Topics_Topic_TopicId", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Topics_Topic_TopicId", "Cours")]
        public EntityCollection<Cours> Courses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Topics_Topic_TopicId", "Cours");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Topics_Topic_TopicId", "Cours", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KelasiModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="registeredDate">Initial value of the RegisteredDate property.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.Boolean gender, global::System.DateTime registeredDate)
        {
            User user = new User();
            user.UserId = userId;
            user.Gender = gender;
            user.RegisteredDate = registeredDate;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private global::System.String _DOB;
        partial void OnDOBChanging(global::System.String value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.Boolean _Gender;
        partial void OnGenderChanging(global::System.Boolean value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegisteredDate
        {
            get
            {
                return _RegisteredDate;
            }
            set
            {
                OnRegisteredDateChanging(value);
                ReportPropertyChanging("RegisteredDate");
                _RegisteredDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegisteredDate");
                OnRegisteredDateChanged();
            }
        }
        private global::System.DateTime _RegisteredDate;
        partial void OnRegisteredDateChanging(global::System.DateTime value);
        partial void OnRegisteredDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Users_Authors_dbo_Users_User_UserId", "Users_Authors")]
        public EntityCollection<Users_Authors> Users_Authors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Users_Authors>("KelasiModel.FK_dbo_Users_Authors_dbo_Users_User_UserId", "Users_Authors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Users_Authors>("KelasiModel.FK_dbo_Users_Authors_dbo_Users_User_UserId", "Users_Authors", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KelasiModel", Name="Users_Authors")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users_Authors : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users_Authors object.
        /// </summary>
        /// <param name="authorId">Initial value of the AuthorId property.</param>
        public static Users_Authors CreateUsers_Authors(global::System.Int32 authorId)
        {
            Users_Authors users_Authors = new Users_Authors();
            users_Authors.AuthorId = authorId;
            return users_Authors;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuthorId
        {
            get
            {
                return _AuthorId;
            }
            set
            {
                if (_AuthorId != value)
                {
                    OnAuthorIdChanging(value);
                    ReportPropertyChanging("AuthorId");
                    _AuthorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuthorId");
                    OnAuthorIdChanged();
                }
            }
        }
        private global::System.Int32 _AuthorId;
        partial void OnAuthorIdChanging(global::System.Int32 value);
        partial void OnAuthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bio
        {
            get
            {
                return _Bio;
            }
            set
            {
                OnBioChanging(value);
                ReportPropertyChanging("Bio");
                _Bio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bio");
                OnBioChanged();
            }
        }
        private global::System.String _Bio;
        partial void OnBioChanging(global::System.String value);
        partial void OnBioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> User_UserId
        {
            get
            {
                return _User_UserId;
            }
            set
            {
                OnUser_UserIdChanging(value);
                ReportPropertyChanging("User_UserId");
                _User_UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_UserId");
                OnUser_UserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _User_UserId;
        partial void OnUser_UserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUser_UserIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId", "Cours")]
        public EntityCollection<Cours> Courses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId", "Cours");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId", "Cours", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId1", "Cours")]
        public EntityCollection<Cours> Courses1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId1", "Cours");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_Author_AuthorId1", "Cours", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Courses_dbo_Users_Authors_AuthorI_AuthorId", "Cours")]
        public EntityCollection<Cours> Courses2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_AuthorI_AuthorId", "Cours");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cours>("KelasiModel.FK_dbo_Courses_dbo_Users_Authors_AuthorI_AuthorId", "Cours", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KelasiModel", "FK_dbo_Users_Authors_dbo_Users_User_UserId", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KelasiModel.FK_dbo_Users_Authors_dbo_Users_User_UserId", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KelasiModel.FK_dbo_Users_Authors_dbo_Users_User_UserId", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("KelasiModel.FK_dbo_Users_Authors_dbo_Users_User_UserId", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("KelasiModel.FK_dbo_Users_Authors_dbo_Users_User_UserId", "User", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
